# Generated by Django 6.0.3 on 2026-03-31 14:04

import advertisement_center.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('video', models.FileField(upload_to='commercial/%Y/%m/%d/', validators=[advertisement_center.validators.video_validator])),
                ('processing_status', models.CharField(choices=[('processing', 'Processing'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_duration', models.PositiveIntegerField(default=0)),
                ('video_format', models.CharField(blank=True, choices=[('mp4', 'MP4'), ('mov', 'MOV'), ('mkv', 'MKV')], default='', max_length=10)),
                ('size_in_bytes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
